### ISSUE TITLE
Cannot rob xaos

### ISSUE THREAD

**Issue by dbladez** [hexafluoride/topkek#1]
There appears to be a bug that does not allow anyone to rob xaos. Please fix this, thanks.

**Comment by dbladez** [comment]
14:43 <&svchost> .mug xaos
14:43 <%topkek_2000>   POLICE   Its the police! looks like u got caught. thats 5 minutes the big house for you!(refnum=3)
14:46 <&dbladez> .mug xaos
14:46 <%topkek_2000>   POLICE   Its the police! looks like u got caught. thats 5 minutes the big house for you!(refnum=7)
14:58 <&svchost> .mug xaos
14:58 <%topkek_2000>   POLICE   Its the police! looks like u got caught. thats 5 minutes the big house for you!(refnum=15)
14:59 <&dbladez> .mug xaos
14:59 <%topkek_2000>   POLICE   Its the police! looks like u got caught. thats 5 minutes the big house for you!(refnum=16)
15:07 <&dbladez> .mug xaos
15:07 <%topkek_2000>   POLICE   Its the police! looks like u got caught. thats 5 minutes the big house for you!(refnum=21)
15:28 <&svchost> .mug xaos
15:28 <%topkek_2000>   POLICE   Its the police! looks like u got caught. thats 5 minutes the big house for you!(refnum=22)
15:28 <&svchost> fucking shit ass cunt fuck
15:32 <&dbladez> .mug xaos
15:32 <%topkek_2000>   POLICE   Its the police! looks like u got caught. thats 5 minutes the big house for you!(refnum=23)
15:39 <&svchost> .mug xaos
15:39 <%topkek_2000>   POLICE   Its the police! looks like u got caught. thats 5 minutes the big house for you!(refnum=24)
15:54 <&dbladez> .mug xaos
15:54 <%topkek_2000>   POLICE   Its the police! looks like u got caught. thats 5 minutes the big house for you!(refnum=25)

**Comment by itsrachelfish** [comment]
Fake news. Please close this issue.

```
14:08 <&dbladez> .mug xaos
14:08 <%topkek_2000> u manage to steal $1,005,156,907,066($1,005,156,907,066 + 0 tickets) off xaos(refnums: success=33, amount=34, t_amount=35)
14:08 <&dbladez> AHAHAHAHAHAHAHAHAHAHAHAHAH
14:08 <&dbladez> I FUCKING WIN. I AM THE WINNER.
```

**Comment by hexafluoride** [comment]
@dbladez, you can verify whether this is a bug or not using the [Auditor tool](https://github.com/hexafluoride/ProbablyFair/releases/tag/v1.1) from my provably fair RNG library on the [audit file](http://hexafluoride.dryfish.net/audit-files/2017-11-27-92884029589e076f8b2ebb3be59f9ef2762098de70cde42541428447f1be4138) pertaining to the day of your complaint. I've ran it for you:

```
C:\Users\Administrator\Downloads>auditor -r 3,7,15,16,21,22,23,24,25,33 2017-11-27-92884029589e076f8b2ebb3be59f9ef2762098de70cde42541428447f1be4138
[Time=11/27/2017 7:43:50 PM, Tag=mug[0.4], Index=3, Type=Boolean, Result=False, RawResult=7b7e..ddfe]: verified
[Time=11/27/2017 7:46:42 PM, Tag=mug[0.4], Index=7, Type=Boolean, Result=False, RawResult=a9fa..5aa7]: verified
[Time=11/27/2017 7:58:28 PM, Tag=mug[0.4], Index=15, Type=Boolean, Result=False, RawResult=b39b..a2e5]: verified
[Time=11/27/2017 7:59:35 PM, Tag=mug[0.4], Index=16, Type=Boolean, Result=False, RawResult=882f..a745]: verified
[Time=11/27/2017 8:07:24 PM, Tag=mug[0.4], Index=21, Type=Boolean, Result=False, RawResult=80c0..958e]: verified
[Time=11/27/2017 8:28:36 PM, Tag=mug[0.4], Index=22, Type=Boolean, Result=False, RawResult=e9b7..0fb1]: verified
[Time=11/27/2017 8:32:03 PM, Tag=mug[0.4], Index=23, Type=Boolean, Result=False, RawResult=7656..184e]: verified
[Time=11/27/2017 8:39:35 PM, Tag=mug[0.4], Index=24, Type=Boolean, Result=False, RawResult=eee9..ca08]: verified
[Time=11/27/2017 8:54:01 PM, Tag=mug[0.4], Index=25, Type=Boolean, Result=False, RawResult=e5b2..0f4a]: verified
[Time=11/27/2017 9:08:43 PM, Tag=mug[0.4], Index=33, Type=Boolean, Result=True, RawResult=d25c..d929]: verified
10 record(s), 10 valid/0 invalid

Generator hash: 92884029589e076f8b2ebb3be59f9ef2762098de70cde42541428447f1be4138 (cross-reference with .fair)
Generator seed: ea5c4048cc9648c24ec86cbd28c7cf326cd21f4824dd9789812e3d7eb2d8090e
Audit result: success
```

=)
